#!/usr/bin/env bash
read -p "Press ENTER to continue"

echo "Removing legacy..."

./remove-legacy

rm -rf ./build
rm -rf ./temprosnehook
rm -rf ./rosnehook-ipc-server
rm -rf ./rosnehook-ipc-web-panel
rm -rf ./vacbypass-modules
rm -rf ./user_instances
rm -rf ./rosnebot-database
sudo rm -rf /opt/rosnehook/ipc
sudo rm /opt/rosnehook/bin/librosnehook-textmode.so
